# Generated by Django 2.1.5 on 2019-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itb', models.FloatField(blank=True, null=True)),
                ('tempamb', models.FloatField(blank=True, null=True)),
                ('tiempodm', models.IntegerField(blank=True, null=True)),
                ('dfc', models.BooleanField(blank=True, null=True)),
                ('tiempodfc', models.IntegerField(blank=True, null=True)),
                ('imagenes', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
    ]
